# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rack_csrf"
gem "rake"
gem "puma"
gem "roda"
gem "roda-i18n"
gem "tilt"
gem "sassc"
gem "sequel"
gem "sqlite3"
gem "mobility"
gem "mail"

gem "letter_opener"
gem "pry"
